apiVersion: v1
kind: Pod
metadata:
  name: busybox-1-28
spec:
  containers:
  - name: c1
    image: busybox:1.28
    command: ['sh', '-c', 'sleep 900']

---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-stable
spec:
  containers:
  - name: c2
    image: busybox:stable
    command: ['sh', '-c', 'sleep 900']

---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-latest
spec:
  containers:
  - name: c3
    image: alpine:latest
    command: ['sh', '-c', 'sleep 900']